language: node_js
os: linux
sudo: required
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - psql -c 'create database sms;' -U postgres
script:
  - npm test
  - npm run coveralls
node_js: "10"
cache:
  directories:
    - node_modules
install: npm install && npm run migrate
